# User Settings | Edit there as per required

title: SellSecure Tech
url: "https://sellsecure.github.io/"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    SellSecure Tech<span class="faded">'s blog</span>

email: xavier.coiffard@sellsecure.com
author: sellsecure
# This description will show up in google search results
# (for index page) etc.
description: >
    Tech blog of SELL Secure team

# This will what will show against &copy; in the footer
copyright: SELLSECURE
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    N'hésitez pas à échanger avec nous sur ce sujet via twitter: @SLSecure
about_footer: true

twitter_username: SLsecure
github_username: sellsecure

favicon: false
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: 

# Social Stuff | open graph and twitter cards
# og_image: "images/accent.png" # This will show in facebook thumbnails
# twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
